region         = "us-east-1"
key_name       = "mi-llave-ec2-grupo-final"
ami            = "ami-000d841032e72b43c"
instance_type  = "t2.micro"
bucket_salida  = "output-bucket-covid-test"
bucket_entrada = "input-bucket-covid-test"
