name: Deploy EC2 Consumer with Terraform

on:
  push:
    branches: [main]

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:  
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Clona el repositorio
        uses: actions/checkout@v3

      - name: Instala Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.6.6"

      - name: Verifica variables AWS
        run: |
          if [ -z "$AWS_ACCESS_KEY_ID" ]; then
            echo "NO HAY AWS_ACCESS_KEY_ID"
            exit 1
          fi
          if [ -z "$AWS_SECRET_ACCESS_KEY" ]; then
            echo "NO HAY AWS_SECRET_ACCESS_KEY"
            exit 1
          fi
          echo "Variables de AWS presentes."
        

      - name: Terraform Init
        run: terraform init
        working-directory: .
      

      - name: Terraform Validate
        run: terraform validate
        working-directory: .
       

      - name: Terraform Plan
        run: terraform plan
        working-directory: .
        

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: .
        
