name: Deploy EC2 Consumer with Terraform

on:
  push:
    branches: [main]

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repo
        uses: actions/checkout@v3

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.6.6"

      - name: Inicializar Terraform
        run: terraform init
        working-directory: ./EC2-DBand-json  # Cambia la ruta a donde están tus .tf

      - name: Validar Terraform
        run: terraform validate
        working-directory: ./EC2-DBand-json

      - name: Aplicar Terraform
        run: terraform apply -auto-approve
        working-directory: ./EC2-DBand-json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
